# Build application
name: Build & Test
on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - main
      - develop

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  models: read
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: warp-ubuntu-2204-x64-2x
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Build docker containers
        uses: docker/bake-action@v6
        with:
          files: |
            docker-bake.hcl
          push: false
          load: true
          allow: network.host,security.insecure,ssh
          source: .
          targets: test
