# Build application
name: Build & Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Build docker containers
        uses: docker/bake-action@v6
        with:
          files: |
            docker-bake.hcl
          push: false
          load: false
          allow: network.host,security.insecure,ssh
          source: .
          targets: default
